ARG PYTHON_VERSION=3.10
ARG OS_DISTRO=windowsservercore

FROM python:${PYTHON_VERSION}-${OS_DISTRO}

ARG PYTHON_VERSION
ARG OS_DISTRO

ENV PYTHON_VERSION=${PYTHON_VERSION}
ENV OS_DISTRO=${OS_DISTRO}

RUN certutil -generateSSTFromWU roots.sst; certutil -addstore -f root roots.sst; del roots.sst

WORKDIR /app

COPY . .

RUN pip install .

RUN nodeenv --list

RUN nodeenv node

RUN node\Scripts\node --version